# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.

require 'cucumber/rails'
require 'capybara-screenshot/cucumber'
require 'database_cleaner'
require 'database_cleaner/cucumber'

ActionController::Base.allow_rescue = false

# disable cucumber cleaner and enabling our own with a different strategy
Cucumber::Rails::Database.autorun_database_cleaner = false
DatabaseCleaner.strategy = :truncation, { pre_count: true }

Capybara.configure do |config|
  config.javascript_driver = :webkit
end

# Capybara::Webkit.configure do |config|
#   config.allow_unknown_urls
#   config.skip_image_loading
# end

Cucumber::Rails::Database.javascript_strategy = :truncation

